FROM ubuntu@sha256:376209074d481dca0a9cf4282710cd30a9e7ff402dea8261acdaaf57a18971dd

ARG DEBIAN_FRONTEND="noninteractive"

ENV \
  APP_DIR="/app" \
  CONFIG_DIR="/config" \
  PUID="1000" \
  PGID="1000" \
  UMASK="002" \
  TZ="Etc/UTC" \
  ARGS=""
ENV \
  XDG_CONFIG_HOME="${CONFIG_DIR}/.config" \
  XDG_CACHE_HOME="${CONFIG_DIR}/.cache" \
  XDG_DATA_HOME="${CONFIG_DIR}/.local/share" \
  XDG_RUNTIME_DIR="/tmp/run/user/app" \
  LANG="en_US.UTF-8" \
  LANGUAGE="en_US:en" \
  LC_ALL="en_US.UTF-8" \
  TERM="xterm"
ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=2

# https://github.com/just-containers/s6-overlay/releases
ARG S6_VERSION="v2.2.0.3"
ARG OVERLAY_ARCH="amd64"

# install s6-overlay
ADD https://github.com/just-containers/s6-overlay/releases/download/${S6_VERSION}/s6-overlay-${OVERLAY_ARCH}-installer /tmp/
RUN chmod +x /tmp/s6-overlay-${OVERLAY_ARCH}-installer && /tmp/s6-overlay-${OVERLAY_ARCH}-installer / && rm /tmp/s6-overlay-${OVERLAY_ARCH}-installer

# install packages
RUN \
#nstall apt-utils and locale
  apt-get update && \
  apt-get install -y \
    apt-utils \
    locales \
    tzdata && \
# install packages
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    p7zip-full \
    python3 \
    unrar \
    unzip \
    wget2 && \
# generate locale
  locale-gen en_US.UTF-8 && \
  apt-get install -y --reinstall ca-certificates && \
# make directories
  mkdir -p \
  "${APP_DIR}" \
  "${CONGIG_DIR}" && \
  mv /usr/bin/with-contenv /usr/bin/with-contenvb && \
# create user
  useradd -u "${PUID}" -U -d "${CONFIG_DIR}" -s /bin/false nobody && \
  usermod -G users nobody && \
# clean up ##
  apt-get autoremove && \
  apt-get clean && \
  rm -rf \
    /tmp/* \
    /var/lib/apt/l

# add local files
COPY root/ /

VOLUME ["${CONFIG_DIR}"]
ENTRYPOINT ["/init"]

# Build arugments
ARG BUILD_DATE
ARG BUILD_REF
ARG BUILD_VERSION
ARG BUILD_REPOSITORY
ARG BUILD_ARCHITECTURE
ENV BUILD_ARCHITECTURE=$BUILD_ARCHITECTURE

# Labels
LABEL \
    maintainer="xthursdayx" \
    org.opencontainers.image.title="Ubuntu-Baseimage for ${BUILD_ARCH}" \
    org.opencontainers.image.authors="xthursdayx" \
    org.opencontainers.image.licenses="GLP-3.0" \
    org.opencontainers.image.url="https://hub.docker.com/r/xthursdayx/baseimage-ubuntu" \
    org.opencontainers.image.source="https://github.com/${BUILD_REPOSITORY}" \
    org.opencontainers.image.documentation="https://github.com/${BUILD_REPOSITORY}/blob/main/README.md" \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.revision=${BUILD_REF} \
    org.opencontainers.image.version=${BUILD_VERSION}
